export const FETCH_RECIPES = 'FETCH_RECIPES';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_ERROR = 'FETCH_RECIPES_ERROR';

export const SET_SEARCHED_RECIPES = 'SET_SEARCHED_RECIPES';
export const ADD_RECIPE = 'ADD_RECIPE';
