export const FETCH_RECIPES = 'FETCH_RECIPES';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_ERROR = 'FETCH_RECIPES_ERROR';

export const SET_SEARCHED_RECIPES = 'SET_SEARCHED_RECIPES';
export const ADD_RECIPE = 'ADD_RECIPE';

//navigation
export const SET_TAB = 'SET_TAB';
export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD';
export const NAVIGATION_BACK = 'NAVIGATION_BACK';
